apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: sentiment-llm
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: llm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
