apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentiment-api-data
  namespace: sentiment
  labels:
    app.kubernetes.io/name: sentiment-api
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
