version: "3.9"

services:
  gitea:
    image: gitea/gitea:1.24.6
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db
      - GITEA__security__INSTALL_LOCK=true
      # WARNING: SECRET_KEY is hardcoded for local development only.
      # You MUST change this value for any non-local or production environment!
      - GITEA__security__SECRET_KEY=local-dev-secret
      - GITEA__server__PROTOCOL=https
      - GITEA__server__DOMAIN=host.containers.internal
      - GITEA__server__ROOT_URL=https://host.containers.internal:3000/
      - GITEA__server__CERT_FILE=/certs/server.crt
      - GITEA__server__KEY_FILE=/certs/server.key
      - GITEA__server__SSH_PORT=30022
      - GITEA__server__SSH_LISTEN_PORT=22
      - GITEA__service__DISABLE_REGISTRATION=true
      - GITEA__service__DEFAULT_KEEP_EMAIL_PRIVATE=true
      - GITEA__service__DEFAULT_ALLOW_CREATE_ORGANIZATION=true
      - GITEA__packages__ENABLED=true
      - GITEA__packages__CONTAINER__ENABLED=true
      - GITEA__packages__CONTAINER__REGISTRY_HTTP__PROTOCOL=https
      - GITEA__actions__ENABLED=true
      - GITEA_ADMIN_USER=gitea-admin
      - GITEA_ADMIN_PASSWORD=ChangeMe123!
      - GITEA_ADMIN_EMAIL=admin@gitea.local
    volumes:
      - ./external-gitea-data:/data
      - ./certs:/certs:ro
    ports:
      - "3000:3000"
      - "30022:22"
