services:
  api:
    build:
      context: ./api-fastapi-azure-function
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8080:80"
    init: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend-python-flask
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_BASE_URL=http://api:80/api/v1
    depends_on:
      api:
        condition: service_healthy
