# Docker Compose for TypeScript + Vite frontend (standalone)
services:
  frontend-typescript-vite:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: subnet-calculator-frontend-typescript-vite:latest
    ports:
      - "3000:80"
    environment:
      # Point to Container App API
      - VITE_API_BASE_URL=http://localhost:8090/api/v1
