apiVersion: v1
kind: Service
metadata:
  name: signoz-ui
  namespace: observability
  labels:
    app.kubernetes.io/name: signoz-ui
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: signoz
    app.kubernetes.io/instance: signoz
    app.kubernetes.io/name: signoz
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30301
