apiVersion: v1
kind: Service
metadata:
  name: signoz-auth-proxy
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: signoz-auth-proxy
    app.kubernetes.io/component: auth-bridge
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: signoz-auth-proxy
    app.kubernetes.io/component: auth-bridge
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
