apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: azure-apim-simulator-dev
  namespace: azure-apim-sim
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: apim-simulator
      app.kubernetes.io/component: gateway
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: azure-auth-gateway-nginx
            "k8s:io.kubernetes.pod.namespace": azure-auth-dev
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
    # Optional: external APIM gateway (if NGINX Gateway Fabric creates these pods)
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: apim-gateway-nginx
            "k8s:io.kubernetes.pod.namespace": azure-apim-sim
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: api-fastapi-keycloak
            app.kubernetes.io/component: backend
            "k8s:io.kubernetes.pod.namespace": azure-auth-dev
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: keycloak
            app.kubernetes.io/component: identity
            "k8s:io.kubernetes.pod.namespace": azure-entraid-sim
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    - toEntities:
        - kube-apiserver

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: azure-apim-simulator-uat
  namespace: azure-apim-sim
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: apim-simulator-uat
      app.kubernetes.io/component: gateway
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: azure-auth-gateway-nginx
            "k8s:io.kubernetes.pod.namespace": azure-auth-uat
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: api-fastapi-keycloak
            app.kubernetes.io/component: backend
            "k8s:io.kubernetes.pod.namespace": azure-auth-uat
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: keycloak
            app.kubernetes.io/component: identity
            "k8s:io.kubernetes.pod.namespace": azure-entraid-sim
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    - toEntities:
        - kube-apiserver

---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: azure-apim-gateway-ingress
  namespace: azure-apim-sim
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: apim-gateway-nginx
  ingress:
    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: apim-simulator
            app.kubernetes.io/component: gateway
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    - toEntities:
        - kube-apiserver
