apiVersion: v1
kind: Service
metadata:
  name: sentiment-auth-frontend
  labels:
    app.kubernetes.io/name: sentiment-auth-frontend
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: sentiment-auth-frontend
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
