apiVersion: v1
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity
kind: Service
spec:
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity
  ports:
    - name: http
      port: 8080
      targetPort: http
