apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-gateway-tls
  namespace: azure-auth-gateway
spec:
  secretName: platform-gateway-tls
  issuerRef:
    name: mkcert-ca
    kind: ClusterIssuer
  dnsNames:
    - '*.127.0.0.1.sslip.io'
    - argocd.127.0.0.1.sslip.io
    - gitea.127.0.0.1.sslip.io
    - hubble.127.0.0.1.sslip.io
    - dev.127.0.0.1.sslip.io
    - '*.dev.127.0.0.1.sslip.io'
    - uat.127.0.0.1.sslip.io
    - '*.uat.127.0.0.1.sslip.io'
