apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: sentiment-llm
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: llm
spec:
  selector:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: llm
  ports:
    - name: http
      port: 11434
      targetPort: 11434
