apiVersion: v1
kind: Service
metadata:
  name: azurite
  labels:
    app.kubernetes.io/name: azurite
    app.kubernetes.io/component: storage
spec:
  selector:
    app.kubernetes.io/name: azurite
    app.kubernetes.io/component: storage
  ports:
    - name: blob
      port: 10000
      targetPort: blob
    - name: queue
      port: 10001
      targetPort: queue
    - name: table
      port: 10002
      targetPort: table
