name: Build sentiment-api image

on:
  push:
    branches: [main]
    paths:
      - "**"
  workflow_dispatch:

env:
  REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}
  DOCKER_HOST: unix:///var/run/docker.sock
  WORKSPACE_DIR: /tmp/sentiment-api

jobs:
  build:
    runs-on: [self-hosted]
    defaults:
      run:
        shell: sh
    steps:
      - name: Clone repo
        env:
          GITEA_USER: ${{ secrets.REGISTRY_USERNAME }}
          GITEA_PASS: ${{ secrets.REGISTRY_PWD }}
          GITEA_HOST: ${{ secrets.GITEAHOST }}
        run: |
          if [ -z "${GITEA_USER}" ] || [ -z "${GITEA_PASS}" ]; then
            echo "Missing Gitea credentials" >&2
            exit 1
          fi
          CLONE_HOST="${GITEA_HOST:-host.docker.internal:3000}"
          rm -rf "${WORKSPACE_DIR}"
          if echo "${CLONE_HOST}" | grep -q "\.svc\."; then
            PROTOCOL="http"
            SSL_VERIFY="true"
          else
            PROTOCOL="https"
            SSL_VERIFY="false"
          fi
          echo "Cloning from ${PROTOCOL}://${CLONE_HOST}/gitea-admin/sentiment-api"
          git config --global credential.helper store
          printf "protocol=%s\nhost=%s\nusername=%s\npassword=%s\n" "${PROTOCOL}" "${CLONE_HOST}" "${GITEA_USER}" "${GITEA_PASS}" | git credential-store store
          git -c http.sslVerify=${SSL_VERIFY} clone "${PROTOCOL}://${CLONE_HOST}/gitea-admin/sentiment-api" "${WORKSPACE_DIR}"
          cd "${WORKSPACE_DIR}"
          git checkout main

      - name: Log in to registry
        run: |
          echo "${REGISTRY_PWD}" | docker login "${REGISTRY_HOST}" -u "${REGISTRY_USERNAME}" --password-stdin
          echo "Logged in to ${REGISTRY_HOST}"

      - name: Pre-pull base image
        run: |
          for img in node:22-alpine; do
            for i in 1 2 3; do
              echo "Pulling ${img} (attempt ${i}/3)..."
              if docker pull "${img}"; then
                break
              fi
              docker rmi "${img}" 2>/dev/null || true
              sleep 3
            done
          done

      - name: Build and push api image
        working-directory: ${{ env.WORKSPACE_DIR }}
        run: |
          docker build --provenance=false -t "${REGISTRY_HOST}/gitea-admin/sentiment-api:latest" .
          docker push "${REGISTRY_HOST}/gitea-admin/sentiment-api:latest"
          echo "Pushed ${REGISTRY_HOST}/gitea-admin/sentiment-api:latest"
