name: Build azure-auth-sim images

on:
  push:
    branches: [main]
    paths:
      - api-apim-simulator/**
      - api-fastapi-azure-function/**
      - frontend-react/**
      - shared-frontend/**
      - .gitea/workflows/**
  workflow_dispatch:

env:
  REGISTRY_HOST: ${{ secrets.REGISTRY_HOST }}
  REGISTRY_PORT: 3000
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  DOCKER_HOST: unix:///var/run/docker.sock
  WORKSPACE_DIR: /tmp/azure-auth-sim

jobs:
  build:
    runs-on: [local]
    container:
      image: ghcr.io/catthehacker/ubuntu:full-24.04
      options: --entrypoint ""
    defaults:
      run:
        shell: sh
    steps:
      - name: Ensure /bin/bash exists
        run: |
          # Some act-runner images lack /bin/bash; symlink to /bin/sh so actions don't fail.
          if [ ! -x /bin/bash ] && [ -x /bin/sh ]; then
            sudo ln -sf /bin/sh /bin/bash || ln -sf /bin/sh /bin/bash
          fi
      - name: Prepare SSH key
        id: prep_ssh
        env:
          KEY_B64: ${{ secrets.CHECKOUT_SSH_KEY_B64 }}
          KNOWN_B64: ${{ secrets.CHECKOUT_KNOWN_HOSTS_B64 }}
          REGISTRY_CA_B64: ${{ secrets.REGISTRY_CA_B64 }}
        run: |
          if [ -z "${KEY_B64}" ] || [ -z "${KNOWN_B64}" ] || [ -z "${REGISTRY_CA_B64}" ]; then
            echo "Required secret missing (ssh key / known hosts / registry CA)" >&2
            exit 1
          fi
          echo "${KEY_B64}" | base64 -d > /tmp/ci_key
          chmod 600 /tmp/ci_key
          echo "${KNOWN_B64}" | base64 -d > /tmp/ci_known_hosts
          echo "${REGISTRY_CA_B64}" | base64 -d > /tmp/ci_registry_ca.crt
          ls -l /tmp/ci_key /tmp/ci_known_hosts
          if [ ! -s /tmp/ci_key ] || [ ! -s /tmp/ci_known_hosts ] || [ ! -s /tmp/ci_registry_ca.crt ]; then
            echo "Decoded SSH key, known_hosts or registry CA is empty" >&2
            exit 1
          fi
          {
            echo "ssh_key<<EOF"
            cat /tmp/ci_key
            echo "EOF"
            echo "known_hosts<<EOF"
            cat /tmp/ci_known_hosts
            echo "EOF"
            echo "registry_ca<<EOF"
            cat /tmp/ci_registry_ca.crt
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
      - name: Clone repo via SSH
        run: |
          GIT_SSH_COMMAND="ssh -i /tmp/ci_key -o UserKnownHostsFile=/tmp/ci_known_hosts -o StrictHostKeyChecking=yes -o IdentitiesOnly=yes -p 30022" \
            git clone ssh://gitea-admin@127.0.0.1:30022/gitea-admin/azure-auth-sim "${WORKSPACE_DIR}"
          cd "${WORKSPACE_DIR}"
          git checkout main
      - name: Docker info
        working-directory: ${{ env.WORKSPACE_DIR }}
        run: |
          REGISTRY_PORT="${REGISTRY_PORT:-${REGISTRY_HOST#*:}}"
          cert_dir="${HOME}/.docker/certs.d"
          install -d \
            "${cert_dir}/${REGISTRY_HOST}" \
            "${cert_dir}/127.0.0.1:${REGISTRY_PORT}" \
            "${cert_dir}/localhost:${REGISTRY_PORT}"
          echo "${{ steps.prep_ssh.outputs.registry_ca }}" > /tmp/registry-ca.crt
          cp /tmp/registry-ca.crt "${cert_dir}/${REGISTRY_HOST}/ca.crt"
          cp /tmp/registry-ca.crt "${cert_dir}/127.0.0.1:${REGISTRY_PORT}/ca.crt"
          cp /tmp/registry-ca.crt "${cert_dir}/localhost:${REGISTRY_PORT}/ca.crt"
          # Best effort: add to system trust if available
          if [ -d /usr/local/share/ca-certificates ]; then
            cp /tmp/registry-ca.crt /usr/local/share/ca-certificates/gitea-ca.crt
            update-ca-certificates || true
          fi
          if [ -f /etc/ssl/certs/ca-certificates.crt ]; then
            cat /tmp/registry-ca.crt >> /etc/ssl/certs/ca-certificates.crt || true
          fi
          docker info

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Pre-pull base images
        run: |
          echo "Pre-pulling base images with retry (platform: linux/amd64)..."
          for img in mcr.microsoft.com/azure-functions/python:4-python3.11 \
                     ghcr.io/astral-sh/uv:latest \
                     node:22-alpine \
                     nginx:alpine; do
            for i in 1 2 3; do
              echo "Pulling ${img} (attempt ${i}/3)..."
              if docker pull --platform linux/amd64 "${img}"; then
                echo "Successfully pulled ${img}"
                break
              fi
              echo "Retry ${i} failed for ${img}, cleaning up..."
              docker rmi "${img}" 2>/dev/null || true
              sleep 5
            done
          done
          docker images --format "table {{.Repository}}:{{.Tag}}\t{{.Size}}"

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_HOST }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build FastAPI (Keycloak)
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKSPACE_DIR }}/api-fastapi-azure-function
          file: ${{ env.WORKSPACE_DIR }}/api-fastapi-azure-function/Dockerfile
          tags: |
            ${{ env.REGISTRY_HOST }}/gitea-admin/azure-auth-sim-api:latest
          push: true
          provenance: false
          platforms: linux/amd64
          pull: false

      - name: Build APIM simulator
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKSPACE_DIR }}/api-apim-simulator
          file: ${{ env.WORKSPACE_DIR }}/api-apim-simulator/Dockerfile
          tags: |
            ${{ env.REGISTRY_HOST }}/gitea-admin/azure-auth-sim-apim:latest
          push: true
          provenance: false
          platforms: linux/amd64
          pull: false

      - name: Build protected frontend
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORKSPACE_DIR }}
          file: ${{ env.WORKSPACE_DIR }}/frontend-react/Dockerfile
          tags: |
            ${{ env.REGISTRY_HOST }}/gitea-admin/azure-auth-sim-frontend:latest
          push: true
          provenance: false
          platforms: linux/amd64
          build-args: |
            VITE_API_URL=http://localhost:8082
            VITE_API_PROXY_ENABLED=false
            VITE_AUTH_METHOD=oidc
            VITE_OIDC_AUTHORITY=http://localhost:8180/realms/subnet-calculator
            VITE_OIDC_CLIENT_ID=frontend-app
            VITE_OIDC_REDIRECT_URI=http://localhost:3007
            VITE_APIM_SUBSCRIPTION_KEY=stack12-demo-key
            VITE_OIDC_AUTO_LOGIN=true
            NODE_OPTIONS=--max-old-space-size=1024
          outputs: type=registry
          pull: false
