apiVersion: v1
metadata:
  name: api-fastapi-keycloak
  labels:
    app.kubernetes.io/name: api-fastapi-keycloak
    app.kubernetes.io/component: backend
kind: Service
spec:
  selector:
    app.kubernetes.io/name: api-fastapi-keycloak
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: http
