apiVersion: v1
kind: Service
metadata:
  name: apim-simulator
  labels:
    app.kubernetes.io/name: apim-simulator
    app.kubernetes.io/component: gateway
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: apim-simulator
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: 8000
      targetPort: http
      nodePort: 30082
