apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: azure-auth-gateway
  namespace: azure-auth-sim
  labels:
    app.kubernetes.io/name: azure-auth-gateway
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: localhost
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: azure-auth-gateway-route
  namespace: azure-auth-sim
  labels:
    app.kubernetes.io/name: azure-auth-gateway-route
spec:
  parentRefs:
    - name: azure-auth-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /realms
        - path:
            type: PathPrefix
            value: /resources
      backendRefs:
        - name: keycloak
          port: 8080
          kind: Service
    - matches:
        - path:
            type: PathPrefix
            value: /apim
      backendRefs:
        - name: apim-simulator
          port: 8000
          kind: Service
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: oauth2-proxy-frontend
          port: 4180
          kind: Service
