apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-frontend
  labels:
    app.kubernetes.io/name: oauth2-proxy-frontend
    app.kubernetes.io/component: auth-proxy
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: oauth2-proxy-frontend
    app.kubernetes.io/component: auth-proxy
  ports:
    - name: http
      port: 4180
      targetPort: http
      nodePort: 30070
