apiVersion: v1
kind: Service
metadata:
  name: sentiment-api
  namespace: sentiment-app
  labels:
    app.kubernetes.io/name: sentiment-api
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: sentiment-api
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
