apiVersion: v1
kind: Service
metadata:
  name: sentiment-frontend
  namespace: sentiment-app
  labels:
    app.kubernetes.io/name: sentiment-frontend
    app.kubernetes.io/component: frontend
spec:
  selector:
    app.kubernetes.io/name: sentiment-frontend
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
