# Cilium network policies - sourced from Gitea repo
# Note: namespace hardcoded to match terraform default (var.argocd_namespace = "argocd")
# Note: gitea-admin hardcoded to match terraform default (var.gitea_admin_username = "gitea-admin")
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: ssh://git@gitea-ssh.gitea.svc.cluster.local:22/gitea-admin/policies.git
    targetRevision: main
    path: policies/cilium
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
