apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
type: Opaque
stringData:
  # Demo-only placeholder (MetalLB requires this key; rotate for any non-local usage)
  secretkey: "local-metallb-memberlist-secret"
