apiVersion: v1
kind: Service
metadata:
  name: apim-simulator-uat
  labels:
    app.kubernetes.io/name: apim-simulator-uat
    app.kubernetes.io/component: gateway
spec:
  selector:
    app.kubernetes.io/name: apim-simulator-uat
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: 8000
      targetPort: http
