apiVersion: v1
kind: Namespace
metadata:
  name: azure-apim-sim
  labels:
    app.kubernetes.io/part-of: azure-auth-sim
    app.kubernetes.io/managed-by: argocd
    simulates: azure-apim
    kyverno.io/isolate: "true"
