apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: check-team-label
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - kyverno-sandbox
      validate:
        message: "Pods in kyverno-sandbox should have a team label"
        pattern:
          metadata:
            labels:
              team: "?*"
