apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: azure-auth-gateway
spec:
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      hostname: localhost
      allowedRoutes:
        namespaces:
          from: Same
