apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: azure-entraid-keycloak
  namespace: azure-entraid-sim
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/component: identity
  ingress:
    - fromEntities:
        - host
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    # OAuth2 proxy (dev/uat)
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: oauth2-proxy-frontend
            app.kubernetes.io/component: auth-proxy
            "k8s:io.kubernetes.pod.namespace": dev
        - matchLabels:
            app.kubernetes.io/name: oauth2-proxy-frontend
            app.kubernetes.io/component: auth-proxy
            "k8s:io.kubernetes.pod.namespace": uat
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    # Backend API (dev/uat)
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: api-fastapi-keycloak
            app.kubernetes.io/component: backend
            "k8s:io.kubernetes.pod.namespace": dev
        - matchLabels:
            app.kubernetes.io/name: api-fastapi-keycloak
            app.kubernetes.io/component: backend
            "k8s:io.kubernetes.pod.namespace": uat
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    # APIM simulator (dev/uat)
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: apim-simulator
            app.kubernetes.io/component: gateway
            "k8s:io.kubernetes.pod.namespace": azure-apim-sim
        - matchLabels:
            app.kubernetes.io/name: apim-simulator-uat
            app.kubernetes.io/component: gateway
            "k8s:io.kubernetes.pod.namespace": azure-apim-sim
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    # NGINX Gateway data plane (dev/uat) for /realms and /resources (browser -> gateway -> keycloak)
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: azure-auth-gateway-nginx
            "k8s:io.kubernetes.pod.namespace": azure-auth-gateway
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
