apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: azure-auth-gateway
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: azure-auth-gateway-nginx
  ingress:
    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "8443"
              protocol: TCP
  egress:
    # Control-plane service for NGINX Gateway Fabric
    - toServices:
        - k8sService:
            namespace: nginx-gateway
            serviceName: nginx-gateway
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "8443"
              protocol: TCP

    # Control-plane pods (fallback in case toServices matching is unreliable)
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: nginx-gateway
            app.kubernetes.io/name: nginx-gateway
            "k8s:io.kubernetes.pod.namespace": nginx-gateway
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "8443"
              protocol: TCP

    # OAuth2 Proxy (dev/uat)
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: oauth2-proxy-frontend
            app.kubernetes.io/component: auth-proxy
            "k8s:io.kubernetes.pod.namespace": dev
        - matchLabels:
            app.kubernetes.io/name: oauth2-proxy-frontend
            app.kubernetes.io/component: auth-proxy
            "k8s:io.kubernetes.pod.namespace": uat
      toPorts:
        - ports:
            - port: "4180"
              protocol: TCP

    # Keycloak (shared)
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: keycloak
            app.kubernetes.io/component: identity
            "k8s:io.kubernetes.pod.namespace": azure-entraid-sim
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP

    # APIM simulators (shared)
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: apim-simulator
            app.kubernetes.io/component: gateway
            "k8s:io.kubernetes.pod.namespace": azure-apim-sim
        - matchLabels:
            app.kubernetes.io/name: apim-simulator-uat
            app.kubernetes.io/component: gateway
            "k8s:io.kubernetes.pod.namespace": azure-apim-sim
      toPorts:
        - ports:
            - port: "8000"
              protocol: TCP

    # Platform UIs behind the gateway (TLS terminated at the gateway)
    - toServices:
        - k8sService:
            namespace: argocd
            serviceName: argocd-server
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: argocd
            app.kubernetes.io/name: argocd-server
            "k8s:io.kubernetes.pod.namespace": argocd
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
    - toServices:
        - k8sService:
            namespace: gitea
            serviceName: gitea-http
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: gitea
            app.kubernetes.io/name: gitea
            "k8s:io.kubernetes.pod.namespace": gitea
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
    - toServices:
        - k8sService:
            namespace: kube-system
            serviceName: hubble-ui
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            k8s-app: hubble-ui
            "k8s:io.kubernetes.pod.namespace": kube-system
      toPorts:
        - ports:
            - port: "8081"
              protocol: TCP

    # DNS
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": kube-system
            "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
