name: Subnet Calculator Infrastructure Tests

on:
  push:
    branches: [main]
    paths:
      - 'subnet-calculator/infrastructure/azure/**'
      - '.github/workflows/subnet-calculator-infra-tests.yml'
  pull_request:
    branches: [main]
    paths:
      - 'subnet-calculator/infrastructure/azure/**'
      - '.github/workflows/subnet-calculator-infra-tests.yml'
  workflow_dispatch:

jobs:
  shellcheck:
    name: ShellCheck Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck
        run: |
          cd subnet-calculator/infrastructure/azure
          make lint

  bats-tests:
    name: BATS Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install BATS and GNU Parallel
        run: |
          sudo apt-get update
          sudo apt-get install -y bats parallel

      - name: Install BATS support libraries
        run: |
          cd subnet-calculator/infrastructure/azure
          mkdir -p tests/test_helper
          # Remove any existing files/directories and clone fresh
          rm -rf tests/test_helper/bats-support
          git clone \
            https://github.com/bats-core/bats-support \
            tests/test_helper/bats-support
          rm -rf tests/test_helper/bats-support/.git

          rm -rf tests/test_helper/bats-assert
          git clone \
            https://github.com/bats-core/bats-assert \
            tests/test_helper/bats-assert
          rm -rf tests/test_helper/bats-assert/.git

      - name: Run BATS unit tests in parallel batches
        run: |
          cd subnet-calculator/infrastructure/azure/tests
          if ls test_*.bats 1> /dev/null 2>&1; then
            echo "Running BATS tests in parallel batches of 100..."

            # Get total test count
            TOTAL_TESTS=$(bats --count test_*.bats | awk '{sum+=$1} END {print sum}')
            echo "Total tests: $TOTAL_TESTS"

            # Run BATS with parallel execution using --jobs
            # BATS --jobs runs test files in parallel, and each file's tests run sequentially
            # With multiple test files of ~100 tests each, this gives us batch-like behavior
            bats --jobs 4 --tap test_*.bats
          else
            echo "No test files found yet. Skipping tests."
            exit 0
          fi

  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    needs: [shellcheck, bats-tests]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck bats parallel

      - name: Install BATS support libraries
        run: |
          cd subnet-calculator/infrastructure/azure
          mkdir -p tests/test_helper
          # Remove any existing files/directories and clone fresh
          rm -rf tests/test_helper/bats-support
          git clone \
            https://github.com/bats-core/bats-support \
            tests/test_helper/bats-support
          rm -rf tests/test_helper/bats-support/.git

          rm -rf tests/test_helper/bats-assert
          git clone \
            https://github.com/bats-core/bats-assert \
            tests/test_helper/bats-assert
          rm -rf tests/test_helper/bats-assert/.git

      - name: Run quality checks
        run: |
          cd subnet-calculator/infrastructure/azure
          make quality || true
          echo "Quality checks complete"
