name: Azure Static Web Apps CI/CD - Managed Functions

# Deploy frontend and managed API functions together to Azure Static Web Apps
# Suitable for Stack 04 (Managed) and Stack 09 (Managed + Entra ID)
# Functions are deployed to westeurope (managed by SWA)

on:
  push:
    branches:
      - main
    paths:
      - 'subnet-calculator/frontend-typescript-vite/**'
      - 'subnet-calculator/api-fastapi-azure-function/**'
      - '.github/workflows/swa-managed-functions.yml'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'subnet-calculator/frontend-typescript-vite/**'
      - 'subnet-calculator/api-fastapi-azure-function/**'

env:
  NODE_VERSION: '20.x'
  PYTHON_VERSION: '3.11'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          cd subnet-calculator/api-fastapi-azure-function
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build frontend
        run: |
          cd subnet-calculator/frontend-typescript-vite
          npm ci
          # Empty API_URL for managed functions (use /api route)
          VITE_API_URL="" npm run build

      - name: Copy SWA config to dist
        run: |
          cd subnet-calculator/frontend-typescript-vite
          # Copy appropriate config based on authentication
          # For no auth (Stack 04):
          cp ../infrastructure/azure/staticwebapp-managed.config.json dist/staticwebapp.config.json
          # For Entra ID auth (Stack 09), uncomment this line instead:
          # cp ../infrastructure/azure/staticwebapp-entraid.config.json dist/staticwebapp.config.json

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          # App location is the built frontend
          app_location: "subnet-calculator/frontend-typescript-vite/dist"
          # API location is the function app source (SWA will deploy it as managed functions)
          api_location: "subnet-calculator/api-fastapi-azure-function"
          # No output location needed when app_location points to dist
          output_location: ""

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
