name: Terraform Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tfsec:
    name: tfsec Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: false

  tflint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint (terragrunt)
        run: |
          find terraform/terragrunt -name "*.tf" \
            -not -path "*/\.*" \
            -not -path "*/.terraform/*" \
            -not -path "*/.terragrunt-cache/*" \
            -exec dirname {} \; | sort -u | while read dir; do
              echo "Linting $dir"
              (cd "$dir" && tflint --format compact) || true
          done

  terraform-fmt:
    name: Terraform Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive terraform/
